### ISSUE TITLE
Error in Building

### ISSUE THREAD

**Issue by teotro** [efeslab/dolma#1]
Hi all!

I tried to compile your code and it gives me the following error:

**Checking for C header file Python.h... no
Error: Check failed for Python.h header in ['-I/usr/include/python2.7', '-I/usr/include/x86_64-linux-gnu/python2.7']
Two possible reasons:
1. Python headers are not installed (You can install the package python-dev on Ubuntu and RedHat)
2. SCons is using a wrong C compiler. This can happen if CC has the wrong value.
CC = gcc**

Any ideas?
Thanks in advance.

**Comment by kevinloughlin** [comment]
First checks...

1. Are you building on Ubuntu 20.04?
2. Have you run `install_dependencies.sh` in the top-level directory?
3. Are you compiling from the top-level directory with the command `python2 $(which scons) -j$(nproc) build/X86_MESI_Two_Level/gem5.opt`?

**Comment by teotro** [comment]
Thanks for your quick reply.

1.  No, I am building on Ubuntu 18.04. Is this gonna be a problem?

2.  When I am running "install_dependencies.sh" I get :
"Unable to locate package python-is-python3
Unable to locate package python2
Unable to locate package python2-dev"
(All the other requirements are satisfied)

3.  Yes, I have also tried to give full path for python or scons but didnt work either.

**Comment by kevinloughlin** [comment]
The code has only been tested on Ubuntu 20.04. I think python support and package names (especially with regards to python2 vs python3) changed between Ubuntu 18.04 and Ubuntu 20.04, which I believe produces the errors you're encountering in #2. The necessary changes to build on 18.04 _might_ be simple (though I haven't tested this theory). In particular, you could try replacing the relevant package names in `install_dependencies.sh` with those listed for Ubuntu 18.04 on the gem5 site [here](https://www.gem5.org/documentation/general_docs/building). Please let me know if that works. If not, I would recommend using Ubuntu 20.04.

**Comment by teotro** [comment]
I have just successfully compiled your code.

In "dolma/Sconstruct" file, I deleted the two flags in lines 371-372 (that you had previously added). Then it worked fine.

Isnt that weird?

**Comment by kevinloughlin** [comment]
Great to hear, and good catch! I had added those lines in because the gcc version in Ubuntu 20.04 had different warning flags/behavior than previous versions, which made the compilation fail. Thanks for the info!
