### ISSUE TITLE
Not getting build

### ISSUE THREAD

**Issue by noshintabassum74** [efeslab/dolma#3]
python2 $(which scons) -j$(nproc) build/X86_MESI_Two_Level/gem5.opt

I am trying to run this command, but I am not getting what is this (which scons) is referring?Like I am giving command like python2 $scons -j$4 build/X86_MESI_Two_Level/gem5.opt. But there is not build in the root directory, how you are working here then? I need to implement this technique within 2 days, so it would be great if you give me a reply.

**Comment by iangneal** [comment]
@noshintabassum74 `$(which scons)` runs the command `which scons`; this command outputs the absolute path of the `scons` binary. 

For example, on my machine:
```sh
> which scons
/usr/local/bin/scons
```

Similarly, the `nproc` is actually a command that outputs the number of processor cores available on your system.

```sh
> nproc
80
```

The `$(...)` notation indicates a [command substitution](https://www.gnu.org/software/bash/manual/html_node/Command-Substitution.html), which inserts the output of the enclosed command into the main command.

So, if you directly run the following command on your command line:
```sh
> python2 $(which scons) -j$(nproc) build/X86_MESI_Two_Level/gem5.opt 
```

Your shell will automatically run `$(which scons)` and `$(nproc)` for you and substitute them into the build command, so it will effectively run this command for you:
```sh
> python2 /usr/local/bin/scons -j80 build/X86_MESI_Two_Level/gem5.opt
```

Note that the command you posted:
```sh
> python2 $scons -j$4 build/X86_MESI_Two_Level/gem5.opt
```

Will try to use `$scons` and `$4` as variables, which are likely not defined previously, so they will be empty, effectively rendering this command incorrectly as:
```sh
> python2 -j build/X86_MESI_Two_Level/gem5.opt
```
